### ISSUE TITLE
Comfyui error "'Namespace' object has no attribute 'preview_size'"

### ISSUE THREAD

**Issue by popovidis** [logtd/ComfyUI-MochiEdit#16]
Hello, just tried to install this, had this issue upon restarting.

```
Traceback (most recent call last):
  File "/workspace/ComfyUI/nodes.py", line 1941, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspace/ComfyUI/custom_nodes/ComfyUI-MochiEdit/__init__.py", line 3, in <module>
    from .nodes.sampler_custom_node import MochiWrapperSamplerCustomNode
  File "/workspace/ComfyUI/custom_nodes/ComfyUI-MochiEdit/nodes/sampler_custom_node.py", line 7, in <module>
    from ..sampling.sampler import run_sampler
  File "/workspace/ComfyUI/custom_nodes/ComfyUI-MochiEdit/sampling/sampler.py", line 7, in <module>
    from ..utils.callback_utils import get_callback_fn
  File "/workspace/ComfyUI/custom_nodes/ComfyUI-MochiEdit/utils/callback_utils.py", line 9, in <module>
    MAX_PREVIEW_RESOLUTION = args.preview_size
AttributeError: 'Namespace' object has no attribute 'preview_size'

Cannot import /workspace/ComfyUI/custom_nodes/ComfyUI-MochiEdit module for custom nodes: 'Namespace' object has no attribute 'preview_size'
```

**Comment by cazs521** [comment]
我也是这样的报错
